In [1]:
import pandas as pd
import numpy as np

In [2]:
#device list by number of users 
device_list = ['Smart_Phone','Tablet','Laptop','Smart_Watch','Desktop_Computer','Smart_Speaker']

In [3]:
counter = 0
tmp_list = []

#join tables with outer join and fill the empty columns with na

for i in device_list:
    
    tmp_list.append(i)
    
    if i =='Smart_Phone':
        big_table = pd.read_csv('predictions_'+str(i)+'.csv')[['ResponseId','actual_use_'+i]]
        print(i)
        print(big_table['actual_use_'+i].sum())
        big_table['Pop_Prediction_'+i] = 1
    else:
        tmp_table = pd.read_csv('predictions_'+str(i)+'.csv')[['ResponseId','actual_use_'+i]]
        print(i)
        print(tmp_table['actual_use_'+i].sum())
        big_table = pd.merge(tmp_table,big_table,on='ResponseId',how='outer')
        big_table['Pop_Prediction_'+i] = 1

for i in device_list:
    
    big_table['Pop_Prediction_'+i] = 1

Smart_Phone
406
Tablet
367
Laptop
324
Smart_Watch
234
Desktop_Computer
151
Smart_Speaker
133

In [4]:
# total column is the number of device of each user in total
big_table['total'] = 6 - big_table.isna().sum(axis=1)

In [5]:
big_table.head(55)

,ResponseId,actual_use_Smart_Speaker,actual_use_Desktop_Computer,actual_use_Smart_Watch,actual_use_Laptop,actual_use_Tablet,actual_use_Smart_Phone,Pop_Prediction_Smart_Phone,Pop_Prediction_Tablet,Pop_Prediction_Laptop,Pop_Prediction_Smart_Watch,Pop_Prediction_Desktop_Computer,Pop_Prediction_Smart_Speaker,total
0,R_1nMWohRx9GqqAVO,0.0,NaN,NaN,NaN,0.0,1.0,1,1,1,1,1,1,3
1,R_2Y9VtN47I8zNzt5,0.0,NaN,1.0,NaN,NaN,0.0,1,1,1,1,1,1,3
2,R_3iFmF3BJNIHlN1P,0.0,1.0,0.0,0.0,NaN,0.0,1,1,1,1,1,1,5
3,R_3noNQ4Mw6T4xCdW,0.0,1.0,NaN,NaN,NaN,0.0,1,1,1,1,1,1,3
4,R_3neFuKoBL4y7nqB,0.0,NaN,1.0,0.0,0.0,0.0,1,1,1,1,1,1,5
5,R_3064ssujf9VyBfr,0.0,NaN,NaN,NaN,1.0,0.0,1,1,1,1,1,1,3
6,R_12tCSRX3XVJH8xh,0.0,NaN,NaN,NaN,1.0,NaN,1,1,1,1,1,1,2
7,R_1pGOFCAsPVmlDyQ,0.0,1.0,NaN,1.0,1.0,0.0,1,1,1,1,1,1,5
8,R_1PaW7suoup0kcxr,0.0,0.0,NaN,0.0,NaN,NaN,1,1,1,1,1,1,3
9,R_33e5HpkE6c2AAr0,0.0,NaN,NaN,1.0,NaN,0.0,1,1,1,1,1,1,3
10,R_6Sc0M0NONRa6OeB,0.0,0.0,0.0,1.0,1.0,1.0,1,1,1,1,1,1,6
11,R_3HYO72cYve7rD0n,0.0,NaN,NaN,0.0,NaN,1.0,1,1,1,1,1,1,3
12,R_3PcrJg75odNFq4X,0.0,0.0,NaN,1.0,NaN,0.0,1,1,1,1,1,1,4
13,R_3PL834KDDvHqnHV,0.0,NaN,1.0,0.0,0.0,1.0,1,1,1,1,1,1,5
14,R_UMzR8qzJB46ywud,0.0,NaN,0.0,0.0,NaN,1.0,1,1,1,1,1,1,4
15,R_d6xA5sYY95CdqyB,0.0,1.0,NaN,1.0,1.0,1.0,1,1,1,1,1,1,5
16,R_1TtMwXeH9J91JgB,0.0,NaN,NaN,1.0,NaN,0.0,1,1,1,1,1,1,3
17,R_330TK61stqmljI2,0.0,0.0,1.0,NaN,0.0,1.0,1,1,1,1,1,1,5
18,R_2wyiwzHwtt2rfBW,0.0,NaN,NaN,NaN,1.0,0.0,1,1,1,1,1,1,3
19,R_1QENUlPL3eMt4Kk,0.0,NaN,0.0,0.0,0.0,1.0,1,1,1,1,1,1,5
20,R_3OitM59oMn4wCS6,0.0,NaN,0.0,NaN,NaN,1.0,1,1,1,1,1,1,3
21,R_32JfUBlKHMsrFYc,0.0,NaN,0.0,NaN,0.0,1.0,1,1,1,1,1,1,4
22,R_3HizvlrCVP5pDWa,0.0,NaN,1.0,NaN,0.0,0.0,1,1,1,1,1,1,4
23,R_12PXKQK2g7KIv8T,0.0,0.0,1.0,0.0,0.0,1.0,1,1,1,1,1,1,6
24,R_2dXUV3NBNVvU7zM,0.0,NaN,1.0,NaN,NaN,0.0,1,1,1,1,1,1,3
25,R_3ma7OnGb8tvGdfb,0.0,NaN,1.0,NaN,NaN,0.0,1,1,1,1,1,1,3
26,R_Zh6Hu0mpI0rTEOJ,0.0,NaN,NaN,0.0,0.0,NaN,1,1,1,1,1,1,3
27,R_12nihNfsVhQsV3c,0.0,NaN,NaN,NaN,1.0,1.0,1,1,1,1,1,1,3
28,R_urJI3hK1X4hTmF3,0.0,NaN,NaN,1.0,1.0,NaN,1,1,1,1,1,1,3
29,R_eFIblFzErtgRwuB,0.0,NaN,NaN,0.0,NaN,1.0,1,1,1,1,1,1,3
30,R_1ibpfk7hWgowK9n,0.0,NaN,1.0,NaN,NaN,NaN,1,1,1,1,1,1,2
31,R_33fLIdUP9QFqWWd,0.0,NaN,0.0,NaN,1.0,NaN,1,1,1,1,1,1,3
32,R_1pWf0TUkm5Zswlz,0.0,NaN,0.0,NaN,NaN,1.0,1,1,1,1,1,1,3
33,R_2U5jOp0UDm8wPQd,0.0,NaN,1.0,NaN,NaN,NaN,1,1,1,1,1,1,2
34,R_5gSJzhDDrIJKeFr,0.0,NaN,1.0,NaN,NaN,0.0,1,1,1,1,1,1,3
35,R_3MKaM3oSoRNQgf5,0.0,NaN,0.0,0.0,0.0,1.0,1,1,1,1,1,1,5
36,R_syUWYskwnSN2d0J,0.0,NaN,1.0,0.0,0.0,1.0,1,1,1,1,1,1,5
37,R_2aG2wpS0bK3b350,0.0,NaN,0.0,NaN,1.0,0.0,1,1,1,1,1,1,4
38,R_1LdRxhscSK8d9VL,0.0,NaN,NaN,NaN,NaN,1.0,1,1,1,1,1,1,2
39,R_1FsVw9h8MBuGXzv,0.0,NaN,0.0,NaN,NaN,NaN,1,1,1,1,1,1,2
40,R_2dMgmfrlkHxvu5Q,0.0,NaN,NaN,NaN,1.0,0.0,1,1,1,1,1,1,3
41,R_2q3fBfrszDZFx0K,0.0,NaN,NaN,NaN,1.0,0.0,1,1,1,1,1,1,3
42,R_1irssOBtqEU3N7a,0.0,NaN,1.0,NaN,0.0,0.0,1,1,1,1,1,1,4
43,R_331MOp8q1hUlDEo,0.0,0.0,0.0,NaN,NaN,NaN,1,1,1,1,1,1,3
44,R_31oBFgLBWYdqDA4,0.0,NaN,NaN,NaN,0.0,1.0,1,1,1,1,1,1,3
45,R_247bYHcxgjgec8J,0.0,1.0,0.0,1.0,1.0,1.0,1,1,1,1,1,1,6
46,R_22VnihC9Syc6BC2,0.0,NaN,NaN,0.0,1.0,NaN,1,1,1,1,1,1,3
47,R_2alCgp9I05i0YsI,0.0,NaN,NaN,NaN,NaN,1.0,1,1,1,1,1,1,2
48,R_2WSHbQRxcxGmb29,0.0,NaN,0.0,NaN,NaN,1.0,1,1,1,1,1,1,3
49,R_cA7N5R6pKyjxVzr,0.0,NaN,NaN,NaN,1.0,0.0,1,1,1,1,1,1,3
50,R_3KOT4GUJ5Jpt4jj,0.0,1.0,0.0,0.0,0.0,0.0,1,1,1,1,1,1,6
51,R_2OPST8eA8SxVw9O,0.0,NaN,1.0,NaN,0.0,1.0,1,1,1,1,1,1,4
52,R_3qTE9H0Fu6Eoit6,0.0,NaN,NaN,0.0,1.0,1.0,1,1,1,1,1,1,4
53,R_2eOp94V0mDPot2q,0.0,NaN,1.0,0.0,0.0,1.0,1,1,1,1,1,1,5
54,R_3DtHNwoxio3x1ul,0.0,NaN,NaN,NaN,NaN,NaN,1,1,1,1,1,1,1

In [6]:
#find the average popularity across all device
pop_percentage = np.mean(big_table['total']/6)

In [7]:
pop_percentage

0.4739583333333327

In [8]:
# the number of devices to check for the participant's total number of devices 
big_table['tocheck'] = (big_table['total']*pop_percentage).apply(int)+1

In [9]:
big_table.head(5)

,ResponseId,actual_use_Smart_Speaker,actual_use_Desktop_Computer,actual_use_Smart_Watch,actual_use_Laptop,actual_use_Tablet,actual_use_Smart_Phone,Pop_Prediction_Smart_Phone,Pop_Prediction_Tablet,Pop_Prediction_Laptop,Pop_Prediction_Smart_Watch,Pop_Prediction_Desktop_Computer,Pop_Prediction_Smart_Speaker,total,tocheck
0,R_1nMWohRx9GqqAVO,0.0,NaN,NaN,NaN,0.0,1.0,1,1,1,1,1,1,3,2
1,R_2Y9VtN47I8zNzt5,0.0,NaN,1.0,NaN,NaN,0.0,1,1,1,1,1,1,3,2
2,R_3iFmF3BJNIHlN1P,0.0,1.0,0.0,0.0,NaN,0.0,1,1,1,1,1,1,5,3
3,R_3noNQ4Mw6T4xCdW,0.0,1.0,NaN,NaN,NaN,0.0,1,1,1,1,1,1,3,2
4,R_3neFuKoBL4y7nqB,0.0,NaN,1.0,0.0,0.0,0.0,1,1,1,1,1,1,5,3

In [47]:
error_list = []
error_total = 0
True_Positive = 0
False_Positive = 0
Positive = 0
False_Negative = 0
test = 0
for index, row in big_table.iterrows():
    
    count = row['tocheck']
    
    
    error = 0
    
    for i in range(0,6):
        
        for j in device_list:
            
            if count == 0:
                break
            
            Positive += 1
            
            #if the user own the device (is null) then we check this device
            
            if not pd.isnull(row['actual_use_'+j]): 
                
                if row['actual_use_'+j] == 0:
                    error +=1
                else:
                    True_Positive +=1
                    
                count = count -1
            
    count = 0
    
    #caculate false negative
    
    for i in range(0,6):
        
        for j in device_list:
            if count < row['tocheck']:
                count = count +1
                continue
            
            #if the user own the device (is null) then we check this device and this device is not "popular" for the participant 
            
            if not pd.isnull(row['actual_use_'+j]):
                
                test +=1
                
                if row['actual_use_'+j] == 1:
                    False_Negative +=1
                count = count +1

    error_total += error/row['tocheck']
    error_list.append(error/row['tocheck'])

In [48]:
test

18681

In [49]:
False_Negative

9222

In [50]:
recall = True_Positive/(True_Positive+False_Negative)

In [51]:
recall

0.09650240031351033

In [52]:
precision = True_Positive/Positive

In [53]:
precision

0.3646797482413921

In [54]:
f1 = 2 * recall * precision / (recall + precision)

In [55]:
f1

0.1526185311434769

In [56]:
error_total

607.3333333333333

In [57]:
acurracy = 1-np.mean(error_list)

In [58]:
acurracy

0.4870495495495496

In [13]:
big_table.shape

(1184, 15)

In [18]:
1-(377.3/1184)

0.6813344594594595